/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.daniel.gui;

/**
 *
 * @author Daniel
 */
public class GUICadastroEspacoCafe extends javax.swing.JInternalFrame {

    /** Creates new form GUICadastroEspacoCafe */
    public GUICadastroEspacoCafe() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLblNomeEspacoCafe = new javax.swing.JLabel();
        jTxtNomeEspacoCafe = new javax.swing.JTextField();
        jLblLotacaoEspacoCafe = new javax.swing.JLabel();
        jTxtLotacaoEspacoCafe = new javax.swing.JTextField();
        BtCadastrarEspacoCafe = new javax.swing.JButton();
        BtSairEspacoCafe = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CADASTRO DO ESPAÇO CAFÉ");

        jLblNomeEspacoCafe.setText("NOME");

        jLblLotacaoEspacoCafe.setText("LOTAÇÃO");

        BtCadastrarEspacoCafe.setText("CADASTRAR");

        BtSairEspacoCafe.setText("SAIR");
        BtSairEspacoCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSairEspacoCafeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblLotacaoEspacoCafe)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTxtLotacaoEspacoCafe)
                                .addComponent(jLblNomeEspacoCafe, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(BtCadastrarEspacoCafe)
                                    .addGap(18, 18, 18)
                                    .addComponent(BtSairEspacoCafe))
                                .addComponent(jTxtNomeEspacoCafe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblNomeEspacoCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNomeEspacoCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblLotacaoEspacoCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTxtLotacaoEspacoCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtCadastrarEspacoCafe)
                    .addComponent(BtSairEspacoCafe))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtSairEspacoCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSairEspacoCafeActionPerformed
        dispose();
    }//GEN-LAST:event_BtSairEspacoCafeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadastrarEspacoCafe;
    private javax.swing.JButton BtSairEspacoCafe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblLotacaoEspacoCafe;
    private javax.swing.JLabel jLblNomeEspacoCafe;
    private javax.swing.JTextField jTxtLotacaoEspacoCafe;
    private javax.swing.JTextField jTxtNomeEspacoCafe;
    // End of variables declaration//GEN-END:variables

}
